services:
  mcp-search:
    image: georgx22/mcp-search:latest
    container_name: mcp-web-search
    restart: always
    ports:
      - "8960:8960"
    environment:
      SEARXNG_URL: URL of your SearxNG instance (e.g. http://localhost:8083/search)
      RELEVANCE_LIMIT: Minimum limit for search result relevance score (float)
      RESULT_NUMBER: Maximum number of results returned (int)
      TAVILY_API_KEY: Your Tavily API key (str)
      SEARXNG_FALLBACK: If the search should fallback to SearxNG if Tavily fails
      EXTRACT_DEPTH: Depth of extraction (basic or advanced) - basic may fail often, but it is quicker
