services:
  Media_creator:
    image: georgx22/mcp-search:latest
    container_name: MCP Web Search
    restart: always
    ports:
      - "8960:8960"
    environment:
      SEARXNG_URL: URL of your SearxNG instance (e.g. http://localhost:8083/search)
      RELEVANCE_LIMIT: Minimum limit for search result relevance score (float)
      RESULT_NUMBER: Maximum number of results returned (int)
